[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = [
    "bun install",
    "cd submodules/linear-mcp && bun install"
]

[phases.build]
cmds = [
    "bun run build"
]

[start]
cmd = "bun run src/server.ts"